<a href="https://colab.research.google.com/github/flatplanet/Pytorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

*  default data type of float32.

* More suitable for deep learning than a numpy array.







In [1]:
import torch
import numpy as np

# **LISTS**


In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.03225423, 0.3084651 , 0.65020865, 0.44783018],
       [0.80171149, 0.46753126, 0.22609405, 0.68730055],
       [0.99595167, 0.97133055, 0.43437056, 0.51199879]])

In [6]:
np2 = np.random.rand(3)
np2

array([0.98806544, 0.01561201, 0.0320204 ])

In [8]:
np3 = np.random.rand(3,4,2)
np3

array([[[0.80256376, 0.63009037],
        [0.87226241, 0.29472825],
        [0.72697469, 0.99012819],
        [0.09468813, 0.78832652]],

       [[0.2352575 , 0.96448542],
        [0.36868963, 0.54715212],
        [0.39080811, 0.57928472],
        [0.8124028 , 0.09816183]],

       [[0.22257863, 0.79591503],
        [0.04001586, 0.4047527 ],
        [0.05562948, 0.04692661],
        [0.28890704, 0.8622099 ]]])

In [5]:
np1.dtype


dtype('float64')

# **TENSORS**

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.9237,  0.6361,  1.3506, -0.2267],
        [-0.3476,  0.6364,  0.1272,  1.2362],
        [ 1.5810, -0.7556,  0.1505,  0.7517]])

In [14]:
tensor_2d.dtype

torch.float32

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0323, 0.3085, 0.6502, 0.4478],
        [0.8017, 0.4675, 0.2261, 0.6873],
        [0.9960, 0.9713, 0.4344, 0.5120]], dtype=torch.float64)

In [13]:
my_tensor.dtype

torch.float64