<a href="https://colab.research.google.com/github/flatplanet/Pytorch-Tutorial-Youtube/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment 



In [1]:
import torch
import numpy as np

In [3]:
# tensor math operations are pretty straight forward
# creating two tensors to play around
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
# Addition
tensor_a + tensor_b
# Items of each index added together

tensor([ 6,  8, 10, 12])

In [ ]:
# Addition Longhand 
torch.add(tensor_a, tensor_b)
# Same thing here, we are just using the add function

tensor([ 6,  8, 10, 12])

In [7]:
# Subtraction 
tensor_b - tensor_a
# same idea, operation applied on each index

tensor([4, 4, 4, 4])

In [ ]:
# Sub Function
torch.sub(tensor_b, tensor_a)
# same idea

tensor([4, 4, 4, 4])

In [9]:
# Multiplication
tensor_a * tensor_b
# same idea, each index multiplied together

tensor([ 5, 12, 21, 32])

In [11]:
# Mul longhand
torch.mul(tensor_a, tensor_b)
# same as above, just function version

tensor([ 5, 12, 21, 32])

In [12]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponents / power
torch.pow(tensor_a, tensor_b)
# 1^5, 2^6, 3^7, 4^8
# the second tensor becomes the power of the first tensor

tensor([    1,    64,  2187, 65536])

In [ ]:
# Another way to write longhand
tensor_a.add(tensor_b)
# doesn't have to use torch.add

tensor([ 6,  8, 10, 12])

In [19]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [20]:
tensor_a

tensor([1, 2, 3, 4])

In [21]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([ 6,  8, 10, 12])